### ISSUE TITLE
Instructs users to pipe from curl to shell

### ISSUE THREAD

**Issue by alphapapa** [justinmayer/tacklebox#5]
[Please](http://output.chrissnell.com/post/69023793377/stop-piping-curl-1-to-sh-1) [don't](http://www.seancassidy.me/dont-pipe-to-your-shell.html) [tell](http://www.djm.org.uk/protect-yourself-from-non-obvious-dangers-curl-url-pipe-sh/) people to `curl | sh`.

**Comment by bucaran** [comment]
Disagree. There are worse things than `curl | sh`

I am not saying `curl | sh` is a great practice and you should check whatever script you pipe into your shell before you do anything, but `curl | sh` it's just convenient. 

I would let users decide.

**Comment by justinmayer** [comment]
While I think the potential MITM attack is very much an edge case, I understand the need to at least encourage folks to inspect the contents before running the installation script. I have modified the docs to include that encouragement.
