### ISSUE TITLE
List of available modules.

### ISSUE THREAD

**Issue by fishequality** [justinmayer/tacklebox#8]
Hi @justinmayer 

Good work on Tacklebox. I was wondering if do you know any plugins/modules/etc that were/are built for Tacklebox besides [Tackle](https://github.com/justinmayer/tackle).

Regards

**Comment by justinmayer** [comment]
Thanks, @fishequality. I'm not aware of any at the moment, but I wouldn't at all be surprised if they are out there.   `><(((*>`
