### ISSUE TITLE
conflict resolution

### ISSUE THREAD

**Issue by automaticgiant** [justinmayer/tacklebox#9]
Is there any facility for conflict resolution between installed plugins/modules/functions?

**Comment by bucaran** [comment]
I believe there is not and if there was it would be quite tricky.

For example creating a prompt and asking user input to make a decision is an option (if running interactively), but _I_ would still find that unpleasent.

Another option is a global level variable that tells the framework what it should do, overrwrite, prompt, abort, etc.

Another option is to keep a list of blessed modules that the framework _knows_ are safe to install and present no name collisions.

**Comment by justinmayer** [comment]
@automaticgiant: None at present. That said, I've never run into any such conflicts. Corner case or no, I'm open to any pull requests related to this topic.  (^_^)
